name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Adjust as needed

      - name: Install dependencies
        run: npm install # or yarn install

      - name: Run tests
        run: npm test # or yarn test

      - name: Check test results and prevent push on failure
        run: |
          if [[ ${{ steps.run-tests.outcome }} == 'failure' ]]; then
            echo "Tests failed, preventing push."
            exit 1
          fi
